name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Set up Android SDK
        uses: android/setup-android@v2
        with:
          sdk-version: '30.x'
          ndk-version: '21.x'
          
      - name: Build and Test
        run: |
          ./gradlew assembleDebug
          ./gradlew check
